import type { Metadata } from 'next';
import localFont from '@next/font/local';
import './globals.css';

//components
import Header from '@/components/Header';
import PageAnimation from '@/components/PageAnimation';
import StairAnimation from '@/components/StairAnimation';

import Footer from '@/components/Footer';

const FuturaPT = localFont({
  src: [
    {
      path: '../../public/fonts/FuturaPT-Light.ttf',
      weight: '300',
    },
    {
      path: '../../public/fonts/FuturaPT-Book.ttf',
      weight: '400',
    },
    {
      path: '../../public/fonts/FuturaPT-Medium.ttf',
      weight: '500',
    },
    {
      path: '../../public/fonts/FuturaPT-Demi.ttf',
      weight: '600',
    },
    {
      path: '../../public/fonts/FuturaPT-Bold.ttf',
      weight: '700',
    },
    {
      path: '../../public/fonts/FuturaPT-ExtraBold.ttf',
      weight: '800',
    },
    {
      path: '../../public/fonts/FuturaPT-Heavy.ttf',
      weight: '900',
    },
  ],
  variable: '--font-FuturaPT',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${FuturaPT.variable} flex flex-col`}>
        <Header />
        <StairAnimation />
        <PageAnimation className="content">{children}</PageAnimation>
        <Footer />
      </body>
    </html>
  );
}
